version : '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: mini_user
      POSTGRES_PASSWORD: superdupersecret
      POSTGRES_DB: mini
    ports:
      - "5433:5432"
    volumes:
      - minify-data:/var/lib/postgresql/data
  app: 

    build: .
    environment:
      DATABASE_URL: postgres://mini_user:superdupersecret@db:5432/mini
      REDIS_URL: redis://redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  redis: 
    image: redis:latest
    ports:
      - "6379:6379"
    

volumes:
  minify-data: